spring:
  application:
    name: Ssenbi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssenbi?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  data:
    redis:
      host: localhost
      port: 6379


coolsms:
  senderPhoneNumber: ${COOLSMS_SENDER}
  api:
    key: ${COOLSMS_API_KEY}
    secret: ${COOLSMS_API_SECRET}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}
  prompts:
    role: ${OPENAI_PROMPT_ROLE}
    role2: ${OPENAI_PROMPT_ROLE2}
    role3: ${OPENAI_PROMPT_ROLE3}
    role4: ${OPENAI_PROMPT_ROLE4}
